#pragma once
#include <string>

inline std::string dx_shader_copy_ps(){ 
  std::string s;
  s += "RFhCQ8zBy2pUDJ18Qc/3elWZyxQBAAAApAIAAAUAAAA0AAAA/AAAAFQBAACIAQAACAIAAFJERUbAAAAAAAAAAAAAAAACAAAAPAAAAAAF//8AgQAAlgAAAFJE";
  s += "MTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAAfAAAAAMAAAAAAAAAAAAAAAAAAAAFAAAAAQAAAAEAAACMAAAAAgAAAAUAAAAEAAAA/////wAAAAABAAAA";
  s += "DQAAAHNhbUxpbmVhclNpbXBsZQB0eERpZmZ1c2UATWljcm9zb2Z0IChSKSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAKurSVNHTlAAAAACAAAACAAAADgA";
  s += "AAAAAAAAAQAAAAMAAAAAAAAADwAAAEQAAAAAAAAAAAAAAAMAAAABAAAAAwMAAFNWX1BPU0lUSU9OAFRFWENPT1JEAKurq09TR04sAAAAAQAAAAgAAAAgAAAA";
  s += "AAAAAAAAAAADAAAAAAAAAA8AAABTVl9UQVJHRVQAq6tTSEVYeAAAAFAAAAAeAAAAaggAAVoAAAMAYBAABQAAAFgYAAQAcBAAAAAAAFVVAABiIAADMhAQAAEA";
  s += "AABlAAAD8iAQAAAAAABIAACNwgAAgENVFQDyIBAAAAAAAEYQEAABAAAARn4QAAAAAAAAYBAABQAAAAFAAAAAAAAAPgAAAVNUQVSUAAAAAgAAAAAAAAAAAAAA";
  s += "AgAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
  s += "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
  return s;
}

inline std::string dx_shader_copy_vs(){ 
  std::string s;
  s += "RFhCQ/NetZBsNAVW3prs7M2DgdMBAAAAFAMAAAUAAAA0AAAAoAAAANQAAAAsAQAAeAIAAFJERUZkAAAAAAAAAAAAAAAAAAAAPAAAAAAF/v8AgQAAPAAAAFJE";
  s += "MTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAATWljcm9zb2Z0IChSKSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAElTR04sAAAAAQAAAAgAAAAgAAAA";
  s += "AAAAAAYAAAABAAAAAAAAAAEBAABTVl9WZXJ0ZXhJRABPU0dOUAAAAAIAAAAIAAAAOAAAAAAAAAABAAAAAwAAAAAAAAAPAAAARAAAAAAAAAAAAAAAAwAAAAEA";
  s += "AAADDAAAU1ZfUE9TSVRJT04AVEVYQ09PUkQAq6urU0hFWEQBAABQAAEAUQAAAGoIAAFgAAAEEhAQAAAAAAAGAAAAZwAABPIgEAAAAAAAAQAAAGUAAAMyIBAA";
  s += "AQAAAGgAAAIBAAAAAQAABxIAEAAAAAAAChAQAAAAAAABQAAAAQAAAFUAAAdCABAAAAAAAAoQEAAAAAAAAUAAAAEAAABWAAAFMgAQAAAAAACGABAAAAAAADIA";
  s += "AA8yIBAAAAAAAEYAEAAAAAAAAkAAAAAAgEAAAIBAAAAAAAAAAAACQAAAAACAvwAAgL8AAAAAAAAAAAAAAAcSABAAAAAAAAoAEAAAAAAACgAQAAAAAAAyAAAK";
  s += "QgAQAAAAAAAaABCAQQAAAAAAAAABQAAAAAAAQAFAAAAAAIA/NgAABTIgEAABAAAAhgAQAAAAAAA2AAAIwiAQAAAAAAACQAAAAAAAAAAAAAAAAAAAAACAPz4A";
  s += "AAFTVEFUlAAAAAkAAAABAAAAAAAAAAMAAAADAAAAAAAAAAIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAA";
  s += "AAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
  return s;
}

